app/urls.py
from django.urls import path
from app.views import *

app_name = 'app'

urlpatterns = [
    path('ifelse/', ifelse, name = 'ifelse'),
    path('ifelif/', ifelif, name = 'ifelif'),
    path('nestedif', nestedif, name = 'nestedif'),
    path('forloop/', forloop, name = 'forloop'),
]

pract4/urls.py
from django.contrib import admin
from django.urls import path, include
import app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def ifelse(request):
    d = {'name' : 'Ajay', 'age' : 4}
    return render(request, 'ifelse.html', context=d)

def ifelif(request):
    d = {'name' : 'Ajay', 'age' : 18}
    return render(request, 'ifelif.html', context = d)

def nestedif(request):
    d = {'a' : 78, 'b' : 85, 'c' : 95}
    return render(request, 'nestedif.html', context = d)

def forloop(request):
    d = {'name' : 'AJAY', 'Hobbies' : ['cricket', 'Football', 'Volleyball', 'chess', 'Badamantion']}
    return render(request, 'forloop.html', context = d)

templates/forloop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>forloop </title>
</head>
<body>
    <center>
        <h1>This if forloop Page</h1>
        <h1>my Name is </h1>
        {% for i in name %}
            <h1>{{i}}</h1>
        
        {% endfor %}

        <h1>My Hobbies are</h1>
        {% for j in Hobbies %}
            <h1>{{j}}</h1>
        
        {% endfor %}
    
        <h1><a href="{% url 'app:nestedif' %}">click here to go for Nestedif page</a></h1>
    </center>
</body>
</html>

templates/ifelif.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>if_elif</title>
</head>
<body>
    <center>
        <h1> This is if_elif page</h1>

        {% if age < 18 %}
            <h1>This is if Block</h1>
            <h1>Your age {{age}} is less than 18. Your are not eligible for vote. </h1>
        
        {% elif age == 18 %}
            <h1>This is elif Block</h1>
            <h1>Your age {{age}} is equal to 18. Your are eligible for vote.</h1>
        
        {% else %}
            <h1>This is else Block</h1>
            <h1>Your age  {{age}} is Greatest than 18. Your are eligible for vote.</h1>
        
        {% endif %}
    </center>
</body>
</html>

templates/ifelse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>if else</title>
</head>
<body>
    <center>
        <h1>
            This is If else page
        </h1>

        <h1>my name is {{name}}</h1>

        {% if age > 20 %}
            <h1>This is If Block</h1>
            <h1>{{age}} is greater then 20</h1>
        
        {% else %}
            <h1>This is else Block</h1>
            <h1>{{age}} is less then 20</h1>
        
        {% endif %}
    </center>
</body>
</html>

templates/nestedif.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nestedif </title>
</head>
<body>
    <center>
        <h1>This is Nested if Conditional</h1>

        {% if a > b %}
            {% if a > c %}
                <h1>This is if Block</h1>
                <h1> {{a}} is Greatest </h1>
            
            {% else %}
                <h1>This is else Block</h1>
                <h1>{{c}} is Greatest</h1>
            
            {% endif %}
        
        {% else %}
            {% if b > c %}
                <h1>This is else-if Block</h1>
                <h1>{{b}} is Greatest</h1>
            
            {% else %}
                <h1>This is else-else Block</h1>
                <h1>{{c}} is Greatest</h1>
            
            {% endif %}

        
        {% endif %}
    
        <h1><a href="{% url 'app:forloop' %}">click here to go for forloop pages</a></h1>
    </center>
</body>
</html>